### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by gmaclennan** [ecometrica/gdal2mbtiles#1]
Hi this looks like a useful tool, but I don't see any usage instructions in the README. Could you add a quick note about how to use it?

**Comment by mghughes** [comment]
After installing with pip, you can run the `gdal2mbtiles --help` command to get a quick usage summary and list of arguments.

But I agree - that information would be useful in the README. I'll keep this issue open to remind us to update it.

**Comment by mghughes** [comment]
Fixed by PR #5
