### ISSUE TITLE
How do I turn on PNG Compression?

### ISSUE THREAD

**Issue by rohitrameshrao** [ecometrica/gdal2mbtiles#11]
Can some one tell me how to turn on PNG compression.

**Comment by mghughes** [comment]
The png compression level is set to level 6 by default. And there's currently no command line option to customize that, sorry.

If you want to dig into the code a bit, there is a `compression` argument to [the `PngRenderer` class](https://github.com/ecometrica/gdal2mbtiles/blob/master/gdal2mbtiles/renderers.py#L99) (and a couple other arguments that might be of interest). In the main method of main.py, you could instantiate your own `PngRenderer` object and [pass that as an argument to the `warp_mbtiles` function](https://github.com/ecometrica/gdal2mbtiles/blob/master/gdal2mbtiles/main.py#L272) - that should let you tweak the compression.
