### ISSUE TITLE
Does gdal2mbtiles support 2x1 top level TMS tiles?

### ISSUE THREAD

**Issue by markerikson** [ecometrica/gdal2mbtiles#2]
gdal2tiles has a `--tmscompatible` flag that forces it to generate 2x1 tiles at the top zoom level, instead of 1x1 (per https://trac.osgeo.org/gdal/changeset/26204 ).  Does gdal2mbtiles support that behavior as well?

**Comment by mghughes** [comment]
Sorry for leaving this so long. Completely missed it.

gdal2mbtiles doesn't have an explicit flag, but it does support different projections. So you could, for example, give a `--spatial-reference` argument of 4326 to generate a map with 2x1 top level tiles.

There is also a `zoom-offset` argument that you could play around with for different projections.

Hope that answers your question.

**Comment by markerikson** [comment]
Heh.  Had completely forgotten about this question myself.  Thanks!
