### ISSUE TITLE
gdal2mbtiles: error: argument --png8: expected one argument

### ISSUE THREAD

**Issue by CUMTsongtao** [ecometrica/gdal2mbtiles#31]
First use, can someone give me an example of the command?

**Comment by tomowatt** [comment]
`gdal2mbtiles test.tif test.mbtiles --png8 4`

As from the README, you can use values from 2 to 256 for `--png8`
Does that help?

**Comment by CUMTsongtao** [comment]
> `gdal2mbtiles test.tif test.mbtiles --png8 4`
> 
> As from the README, you can use values from 2 to 256 for `--png8`
> Does that help?

thank you for your answer, I tried out the command according to your example 
`gdal2mbtiles C:\Users\30901\Desktop\paletted.tif C:\Users\30901\Desktop\test.mbtiles --png8 4 --spatial-reference 4326 --resampling bilinear --coloring gradient --color 0:#ff00ff`

the error log change to this  
"TypeError: LoadLibrary() argument 1 must be str, not None"

detail
`Traceback (most recent call last):
  File "D:\python3.6\Scripts\gdal2mbtiles-script.py", line 11, in <module>
    load_entry_point('gdal2mbtiles==2.1.1', 'console_scripts', 'gdal2mbtiles')()
  File "D:\python3.6\lib\site-packages\gdal2mbtiles\main.py", line 264, in main
    args = parse_args(args=args)
  File "D:\python3.6\lib\site-packages\gdal2mbtiles\main.py", line 231, in parse_args
    args.coloring = coloring_arg(args.coloring)
  File "D:\python3.6\lib\site-packages\gdal2mbtiles\main.py", line 65, in coloring_arg
    from gdal2mbtiles import vips
  File "D:\python3.6\lib\site-packages\gdal2mbtiles\vips.py", line 76, in <module>
    TIFF = LibTiff()
  File "D:\python3.6\lib\site-packages\gdal2mbtiles\vips.py", line 60, in __init__
    self.libtiff = cdll.LoadLibrary(library)
  File "D:\python3.6\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "D:\python3.6\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None`

**Comment by tomowatt** [comment]
`--color "0:#ff00ff"`

You will need to use quotes around the hex code to make it a string

**Comment by CUMTsongtao** [comment]
Thanks . it doesn`t work 
and same error message as above

**Comment by tomowatt** [comment]
So I've run the command with the parameters you've used on a test file and it completed successfully. This was on Ubuntu 18.04 - via WSL - with GDAL 2.4.2 and I can see you are using Windows so I recommend you check that all the requirements for running GDAL on Windows are installed correctly as well as the Python Requirements - as I know there are differences with Linux and Windows installs.

**Comment by CUMTsongtao** [comment]
OK,I will use it on centos7.4 in the future
Can you tell me the list of gdal2mbtiles dependencies and version  you used? 
i will try to configure the environment

**Comment by tomowatt** [comment]
The dependencies are listed in the README and a `pip install` will give the needed requirements. I am using GDAL 2.4.2.
Sorry, I can't help much more!

**Comment by CUMTsongtao** [comment]
It worked last week ! thank you very much !

**Comment by tomowatt** [comment]
Great to hear!

**Comment by CUMTsongtao** [comment]
Hi. i have one question about memory,
I set 8G of memory for the virtual machine Ubuntu18.04,
An error is reported during execution:
`memory error: Unable to allocate 4.73 Gib for an arry with shape(1269761870,) and data type int32`
The source tif : 596M 
How much memory  I need?

**Comment by elfmanryan** [comment]
> Hi. i have one question about memory,
> I set 8G of memory for the virtual machine Ubuntu18.04,
> An error is reported during execution:
> `memory error: Unable to allocate 4.73 Gib for an arry with shape(1269761870,) and data type int32`
> The source tif : 596M
> How much memory I need?

Hi, yes you will need more memory. I am guessing the tif has some compression, so one its unpacked it will be larger (hence the discrepancy between your file size on disk and in memory.) generally int files have good compression as well. Also 8G of memory is not a lot for GIS type operations as we tend to experience lots of arrays! 16G might be a good starting point. 
Hope that helps,

**Comment by CUMTsongtao** [comment]
I replaced it with a computer with 32G memory , the same error message as the last.
I don't think it's a memory problem
`memory error: Unable to allocate 4.73 Gib for an arry with shape(1269761870,) and data type int32`
 it should be an array can't hold so much data.
Ask for your help please.

**Comment by jordiecometrica** [comment]
Are you on a 32-bit machine or with 32-bit binaries? 4 gigabytes is the limit of addressable memory in 32 bits.

**Comment by CUMTsongtao** [comment]
My computer is 64-bit machine and the OS as well, gdal2mbtiles was installed according to README

**Comment by jordiecometrica** [comment]
If you open a Python prompt, are you able to allocate 5 gigabytes of memory? For example, 
```python
import numpy as np
x = np.zeros(5*1024**3, dtype='int8')
```

**Comment by CUMTsongtao** [comment]
`import numpy as np
x = np.zeros(5*1024**3, dtype='int8')`
I tried it , and the code can run on my python3.6.8
