### ISSUE TITLE
Set zoom levels

### ISSUE THREAD

**Issue by benboughton1** [ecometrica/gdal2mbtiles#4]
How do you set zoom levels such as --zoom 10-15?
Is this what the resolution arguments are for?

**Comment by benboughton1** [comment]
No longer an issue.

**Comment by rohitrameshrao** [comment]
How can I do this?

**Comment by mghughes** [comment]
@rohitrameshrao The zoom levels can be set with the `--min-resolution` and `--max-resolution` command line arguments
