### ISSUE TITLE
ValueError: xscale 0.99375 cannot be less than 1.0

### ISSUE THREAD

**Issue by wandergis** [ecometrica/gdal2mbtiles#6]
This tool is awesome,but I just run a sample with a tif file,but i have caught an error as it below,and i don't know how to do with this tif file. can you give me some help?
![image](https://cloud.githubusercontent.com/assets/5799374/14917266/c5fbc816-0e50-11e6-949e-689d8019d5aa.png)

**Comment by spatialhast** [comment]
@wandergis please provide gdalinfo information for raster using command:
`gdalinfo isodata_re.tif`

**Comment by spatialhast** [comment]
@wandergis if raster consist gdalinfo information like:
```
Band 1 Block=22612x1 Type=Int16, ColorInterp=Gray
Band 2 Block=22612x1 Type=Int16, ColorInterp=Undefined
Band 3 Block=22612x1 Type=Int16, ColorInterp=Undefined
```

try change this information on 
```
Band 1 Block=21848x1 Type=Byte, ColorInterp=Red
Band 2 Block=21848x1 Type=Byte, ColorInterp=Green
Band 3 Block=21848x1 Type=Byte, ColorInterp=Blue
```

using command

> gdalwarp -overwrite **-ot Byte** input.tif output.tif

**Comment by wandergis** [comment]
Thanks a lot,I will try it later.

**Comment by mghughes** [comment]
I just ran into this today - I think I have a fix that I'll be able to push out next week.

I realize that this issue is pretty old, but I wasn't able to actually reproduce it until now :)
